
from newsboardapp.models import *       
u1 = User(username = 'u1', password = '123') 
u1.save
u2 = User(username = 'u2', password = '123') 
u2.save()                  
u3 = User(username = 'u3', password = '123') 
u3.save()                  
a1 = Author(full_name = 'a1',user = u1,age = 23)
a1.save()                    
a2 = Author(full_name = 'a2',user = u2,age = 44,email = 'asd@asd.bu')
a2.save()                               
a1.update_rating()
cat1 = Category(name = 'Неизведанное')
cat1.save()          
cat2 = Category(name = 'Важное') 
cat2.save()          
cat3 = Category(name = 'ПОзнавательно') 
cat3.save()          
cat4 = Category(name = 'что там') 
cat4.save()          
post1 = Post(author = a1,caption = 'Важная новость', text = 'эта доска работает в статьях и новостях запрещена обсценная лексика и точка зрения отличная от точки зрения правительства РФ',type = 'Nsave()
post2 = Post(author = a1,caption = 'Порядок приема препарата подавляющего чувства', text = 'вскрыть ампулу, ввести подкожно не реже раз в 12 часов ',type = 'PO') 
post2.save()                                                       
post3 = Post(author = a2,caption = 'ВОзрадуйся народ 105 шестилетка выполнена за 2 месяца', text = 'Это какой-то фуррор!!!!!!!!',type = 'PO') 
post3.save()                                                                 
PostCategory.objects.create(post = post1, сategory = cat1)                                
PostCategory.objects.create(post = post1, сategory = cat3) 
PostCategory.objects.create(post = post2, сategory = cat2) 
PostCategory.objects.create(post = post2, сategory = cat4) 
PostCategory.objects.create(post = post3, сategory = cat2) 
PostCategory.objects.create(post = post3, сategory = cat3) 
comm1 = Comment(post = post1,user = u1 , text = 'i`m first - lol!!!') 
comm1.save()
comm2 = Comment(post = post2,user = u2 , text = 'i`m first - lol!!!') 
comm2.save()                             
comm3 = Comment(post = post3,user = u2 , text = 'i`m first - lol!!!') 
comm3.save()                             
>>> post1.like()       
>>> post1.like()
>>> post1.like()
>>> post1.like()
>>> post1.like()
>>> post1.like()
>>> post1.like()
>>> post1.like()
>>> post1.like()
>>> post1.like()
>>> post2.like() 
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post2.like()
>>> post3.like() 
>>> post3.like()
>>> post3.like()
>>> post3.like()
>>> post3.like()
>>> post3.like()
>>> post3.like()
>>> post3.like()
>>>
>>> post3.like()
>>> a1.update_rating() 
>>> a2.update_rating() 
>>> print(a1.rating)   
78
>>> print(a2.rating)   
27
>>> comm4 = Comment(post = post1,user = u3 , text = ' lol!!!')                    
>>> comm4.save()
>>> comm4.like()                                                                   
>>> comm4.like()
>>> comm4.like()
>>> comm4.like()
>>> comm4.like()
>>> comm4.like()
>>> comm4.dislike() 
>>> comm1.dislike() 
>>> comm1.dislike()
>>> comm1.dislike()
>>> comm1.dislike()
>>> comm1.dislike()
>>> comm1.dislike()
>>> comm1.dislike()
>>> comm1.dislike()
>>> comm1.dislike()
>>> comm2.like()    
>>> comm2.like()
>>> comm2.like()
>>>
>>> comm2.like()
>>> comm2.like()
>>> comm2.like()
>>> comm2.like()
>>> comm2.like()
>>> comm2.like()
>>> comm2.like()
>>> comm3.dislike() 
>>> comm3.dislike()                                                                
>>> comm3.dislike()
>>> comm3.dislike()
>>> comm3.dislike()
>>> comm3.dislike()
>>> comm3.dislike()
>>> comm3.dislike()
>>> a1.update_rating()                                                             
>>> a2.update_rating() 
>>> print(a2.rating)                                                               
53
>>> print(a1.rating) 
113
>>> print(Author.objects.all().order_by('rating')[0].user.username)
u2
>>> print(Author.objects.all().order_by('-rating')[0].user.username)
u1
>>> findpost = Post.objects.filter(type = 'PO').order_by('-rating')[0]
>>> print(findpost.author.user.username)                               
u1
>>> print(findpost.rating)               
16
>>> print(findpost.caption)
Порядок приема препарата подавляющего чувства
>>> print(findpost.preview())
вскрыть ампулу, ввести подкожно не реже раз в 12 часов ...
>>> print(Comment.objects.filter(post = findpost).values('datetime', 'user', 'rating', 'text'))
<QuerySet [{'datetime': datetime.datetime(2024, 8, 23, 21, 18, 34, 860307, tzinfo=datetime.timezone.utc), 'user': 5, 'rating': 10, 'text': 'i`m first - lol!!!'}]>
